version: '2.4'

services:
  apache:
    container_name: apache-dav
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - HTTP_USER=bob
      - HTTP_PASS=123456
    ports:
      - 80:80/tcp
